baseURL = 'https://odysseypta.org/'
languageCode = 'en-us'
title = 'Odyssey PTA'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
# Paginate = 3
#googleAnalytics = ""
enableRobotsTXT = false

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = "near-black"
  author = "Odyssey Program PTA"
  #site_logo = "favicons/favicon-32x32.png"
  #description = ""
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-gray"
  #recent_posts_number = 3
  enableGitInfo = true
  # the next line eliminates the Recents section on the front page because nothing is of section "ignore"
  mainSections = "ignore"

#[[params.ananke_socials]]
#  name = "facebook"
#  url = "https://facebook.com/"
#  follow = false
