baseURL = 'https://odysseypta.org/'
languageCode = 'en-us'
title = 'Odyssey PTA'
theme = 'ananke'

DefaultContentLanguage = "en"
SectionPagesMenu = "main"

# use static robots.txt
enableRobotsTXT = false

[params]
  text_color = "near-black"
  author = "Odyssey Program PTA"
  #site_logo = "favicons/favicon-32x32.png"
  #description = ""
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-gray"
  recent_posts_number = 1
  show_recent_posts = false
  enableGitInfo = true
  # the next line eliminates the Recents section on the front page because nothing is of section "ignore"
  mainSections = "ignore"
